apiVersion: v1
data:
  application_default_credentials.json: <base-64 encoded application_default_credentials.json>
kind: Secret
metadata:
  name: gcr-secret
  namespace: kube-system
  labels:
    app: gcr-creds
    version: v1.2
    kubernetes.io/minikube-addons: gcr-creds
type: Opaque
