apiVersion: v1
kind: ReplicationController
metadata:
  name: awsecr-creds
  namespace: kube-system
  labels:
    version: v1.0
spec:
  replicas: 1
  selector:
    name: awsecr-creds
    version: v1.0
  template:
    metadata:
      labels:
        name: awsecr-creds
        version: v1.0
    spec:
      containers:
      - image: upmcenterprises/awsecr-creds:1.0
        name: awsecr-creds
        args:
        - --aws-account=<AWSAccount>
        imagePullPolicy: Always
        env:
          - name: AWS_ACCESS_KEY_ID
            value: <YourKey>
          - name: AWS_SECRET_ACCESS_KEY
            value: <YourAccessKey>
