apiVersion: v1
kind: ReplicationController
metadata:
  name: awsecr-creds
  namespace: kube-system
  labels:
    version: v1.0
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    name: awsecr-creds
    version: v1.0
  template:
    metadata:
      labels:
        name: awsecr-creds
        version: v1.0
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - image: upmcenterprises/awsecr-creds:1.0
        name: awsecr-creds
        args:
        - --aws-account=[YourAWSAccountId]
        imagePullPolicy: Always
