apiVersion: v1
kind: ReplicationController
metadata:
  name: registry-creds
  namespace: kube-system
  labels:
    version: v1.5
spec:
  replicas: 1
  selector:
    name: registry-creds
    version: v1.5
  template:
    metadata:
      labels:
        name: registry-creds
        version: v1.5
    spec:
      containers:
      - image: upmcenterprises/registry-creds:1.5
        name: registry-creds
        imagePullPolicy: Always
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: registry-creds
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: registry-creds
                key: AWS_SECRET_ACCESS_KEY
          - name: awsaccount
            valueFrom:
              secretKeyRef:
                name: registry-creds
                key: aws-account
          - name: awsregion
            valueFrom:
              secretKeyRef:
                name: registry-creds
                key: aws-region
