apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: Y2hhbmdlbWU=
  AWS_SECRET_ACCESS_KEY: Y2hhbmdlbWU=
  aws-account: Y2hhbmdlbWU=
kind: Secret
metadata:
  name: registry-creds
  namespace: kube-system
  labels:
    app: registry-creds
    version: v1.2
    kubernetes.io/minikube-addons: registry-creds
type: Opaque

data:
  application_default_credentials.json: Y2hhbmdlbWU=
kind: Secret
metadata:
  name: gcr-secret
  namespace: kube-system
  labels:
    app: gcr-creds
    version: v1.2
    kubernetes.io/minikube-addons: gcr-creds
type: Opaque
