apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - image: <aws-accountid>.dkr.ecr.us-east-1.amazonaws.com/nginx
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
        name: busybox
